<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-08T14:46:26 IST" name="Default suite" finished-at="2025-09-08T14:46:47 IST" duration-ms="21540">
    <groups>
    </groups>
    <test started-at="2025-09-08T14:46:26 IST" name="Default test" finished-at="2025-09-08T14:46:47 IST" duration-ms="21540">
      <class name="com.imejob.tests.functional.JobSeekerSignInTest">
        <test-method is-config="true" signature="start()[pri:0, instance:com.imejob.tests.functional.JobSeekerSignInTest@2d1ef81a]" started-at="2025-09-08T14:46:26 IST" name="start" finished-at="2025-09-08T14:46:37 IST" duration-ms="11204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="signInTest(java.lang.String,java.lang.String)[pri:1, instance:com.imejob.tests.functional.JobSeekerSignInTest@2d1ef81a]" started-at="2025-09-08T14:46:37 IST" name="signInTest" data-provider="signInData" finished-at="2025-09-08T14:46:47 IST" duration-ms="9946" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sumair@123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sumair@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://sso.imejob.com/auth/login?callback=https%3A%2F%2Fimejob.com%2Fauth%2Fcallback%3FcontinueUri%3D%2Fdashboard%2Fjob-seeker%2Fapplications&requestType=jobSeeker] but found [https://imejob.com/dashboard/job-seeker/applications]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://sso.imejob.com/auth/login?callback=https%3A%2F%2Fimejob.com%2Fauth%2Fcallback%3FcontinueUri%3D%2Fdashboard%2Fjob-seeker%2Fapplications&requestType=jobSeeker] but found [https://imejob.com/dashboard/job-seeker/applications]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.imejob.tests.functional.JobSeekerSignInTest.signInTest(JobSeekerSignInTest.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:com.imejob.tests.functional.JobSeekerSignInTest@2d1ef81a]" started-at="2025-09-08T14:46:47 IST" name="close" finished-at="2025-09-08T14:46:47 IST" duration-ms="192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.imejob.tests.functional.JobSeekerSignInTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
